#!/usr/bin/env python3
"""
gen_foliage.py
==============

Places trees and shrubs on the terrain where the satellite imagery shows
vegetation, and writes them as a single static Gazebo model.

Method
------
Vegetation is detected per texture pixel with the Excess Green index,
ExG = 2g - r - b on chromaticity-normalised RGB, a standard vegetation
index for RGB imagery. Dark, strongly green pixels are treated as tree
canopy; lighter green as scrub. Candidates are drawn on a jittered grid,
shuffled, and accepted with probability proportional to local vegetation
strength until the caps are reached, so caps thin foliage evenly. Plants
are kept clear of turbine pads, the rover spawn, and (optionally) building
footprints. Each plant stands on the rendered visual heightmap.

Geometry
--------
A tree canopy is three to five overlapping lobes, each a once-subdivided
icosphere (80 faces) with jittered radius and SMOOTH radial normals, so
crowns read as soft, clumpy foliage rather than faceted shapes. Trunks are
tapered hexagonal prisms. Shrubs are one or two smaller lobes.

All trunks share one mesh and canopies are split across four colour
variants, so thousands of plants cost about seven draw calls. Plants are
visual only: no collision.

Caveat for any write-up: the Copernicus DEM is a surface model, so canopy
height is already partly in the terrain. Foliage is decorative context.

Output: models/<terrain>_foliage/{model.sdf, model.config, meshes/*.obj}

Usage
  python3 tools/gen_foliage.py --terrain-model attappadi \
      [--avoid-geojson ~/Downloads/attappadi_osm.geojson]
"""

import argparse
import json
import math
import os
import random

import numpy as np
from PIL import Image

from terrain_io import Terrain, read_turbines


class Mesh:
    """Indexed mesh with per-vertex normals (smooth) or per-face (flat)."""

    def __init__(self):
        self.v, self.n, self.f = [], [], []

    def add_vertex(self, p, nrm):
        self.v.append(p)
        self.n.append(nrm)
        return len(self.v)

    def add_face(self, a, b, c):
        self.f.append((a, b, c))

    def write(self, path, name):
        with open(path, "w") as fh:
            fh.write(f"# Generated by gen_foliage.py\no {name}\n")
            fh.writelines(f"v {p[0]:.2f} {p[1]:.2f} {p[2]:.2f}\n" for p in self.v)
            fh.writelines(f"vn {q[0]:.3f} {q[1]:.3f} {q[2]:.3f}\n" for q in self.n)
            fh.writelines(f"f {a}//{a} {b}//{b} {c}//{c}\n" for a, b, c in self.f)
        return len(self.f)


def icosphere1():
    """Unit icosphere, one subdivision: 42 vertices, 80 faces."""
    t = (1 + 5 ** 0.5) / 2
    v = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0), (0, -1, t), (0, 1, t),
         (0, -1, -t), (0, 1, -t), (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    v = [tuple(c / math.sqrt(sum(k * k for k in p)) for c in p) for p in v]
    f = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11), (1, 5, 9),
         (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8), (3, 9, 4), (3, 4, 2),
         (3, 2, 6), (3, 6, 8), (3, 8, 9), (4, 9, 5), (2, 4, 11), (6, 2, 10),
         (8, 6, 7), (9, 8, 1)]
    cache, out = {}, []

    def mid(a, b):
        key = (min(a, b), max(a, b))
        if key not in cache:
            p = [(v[a][i] + v[b][i]) / 2 for i in range(3)]
            m = math.sqrt(sum(c * c for c in p))
            v.append(tuple(c / m for c in p))
            cache[key] = len(v) - 1
        return cache[key]

    for a, b, c in f:
        ab, bc, ca = mid(a, b), mid(b, c), mid(c, a)
        out += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
    return v, out


SPHERE_V, SPHERE_F = icosphere1()
# Coarse sphere (the base icosahedron) for small shrubs: smooth normals keep
# it soft-looking at a quarter of the triangles.
SPHERE0_V, SPHERE0_F = SPHERE_V[:12], [(0, 11, 5), (0, 5, 1), (0, 1, 7),
    (0, 7, 10), (0, 10, 11), (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6),
    (7, 1, 8), (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
    (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]


def lobe(mesh, cx, cy, cz, rx, rz, rng, jitter=0.12, fine=True):
    """Soft, slightly irregular sphere with smooth radial normals."""
    sv, sf = (SPHERE_V, SPHERE_F) if fine else (SPHERE0_V, SPHERE0_F)
    base = len(mesh.v)
    for x, y, z in sv:
        j = 1.0 + rng.uniform(-jitter, jitter)
        mesh.add_vertex((cx + x * rx * j, cy + y * rx * j, cz + z * rz * j),
                        (x, y, z * rx / rz))
    for a, b, c in sf:
        mesh.add_face(base + a + 1, base + b + 1, base + c + 1)


def trunk(mesh, x, y, z, r0, r1, h, k=6):
    for i in range(k):
        a0 = 2 * math.pi * i / k
        a1 = 2 * math.pi * (i + 1) / k
        nx, ny = math.cos((a0 + a1) / 2), math.sin((a0 + a1) / 2)
        p = [(x + r0 * math.cos(a0), y + r0 * math.sin(a0), z - 0.4),
             (x + r0 * math.cos(a1), y + r0 * math.sin(a1), z - 0.4),
             (x + r1 * math.cos(a1), y + r1 * math.sin(a1), z + h),
             (x + r1 * math.cos(a0), y + r1 * math.sin(a0), z + h)]
        ids = [mesh.add_vertex(q, (nx, ny, 0.15)) for q in p]
        mesh.add_face(ids[0], ids[1], ids[2])
        mesh.add_face(ids[0], ids[2], ids[3])


def load_footprints(path, ter):
    """Building polygons from a GeoJSON export, in world metres, with bboxes."""
    if not path:
        return []
    polys = []
    for ft in json.load(open(os.path.expanduser(path))).get("features", []):
        g, pr = ft.get("geometry") or {}, ft.get("properties") or {}
        if "building" not in pr or g.get("type") not in ("Polygon", "MultiPolygon"):
            continue
        rings = [g["coordinates"][0]] if g["type"] == "Polygon" else \
            [p[0] for p in g["coordinates"]]
        for ring in rings:
            pts = [ter.latlon_to_world(la, lo) for lo, la in ring]
            xs, ys = [p[0] for p in pts], [p[1] for p in pts]
            polys.append((pts, min(xs) - 4, max(xs) + 4, min(ys) - 4, max(ys) + 4))
    return polys


def near_building(px, py, polys):
    for pts, x0, x1, y0, y1 in polys:
        if x0 <= px <= x1 and y0 <= py <= y1:
            return True     # within the footprint plus a 4 m buffer box
    return False


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--terrain-model", required=True)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--avoid-geojson", help="Keep clear of building footprints")
    ap.add_argument("--margin", type=float, default=350.0)
    ap.add_argument("--spacing", type=float, default=7.0)
    ap.add_argument("--max-trees", type=int, default=2500)
    ap.add_argument("--max-shrubs", type=int, default=6000)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    repo = os.path.abspath(os.path.expanduser(args.repo))
    ter = Terrain(os.path.join(repo, "models", args.terrain_model))
    turb = read_turbines(os.path.join(repo, "config", "turbines.yaml"))
    polys = load_footprints(args.avoid_geojson, ter)
    rng = random.Random(args.seed)

    img = np.asarray(Image.open(os.path.join(ter.dir, ter.meta["texture"]))
                     .convert("RGB"), dtype=np.float32)
    ts = img.shape[0]
    s = img.sum(axis=2) + 1e-6
    exg = (2 * img[:, :, 1] - img[:, :, 0] - img[:, :, 2]) / s
    bright = img.mean(axis=2) / 255.0

    xs = [0.0] + [t["x"] for t in turb]
    ys = [0.0] + [t["y"] for t in turb]
    x0 = max(min(xs) - args.margin, -ter.half + 5)
    x1 = min(max(xs) + args.margin, ter.half - 5)
    y0 = max(min(ys) - args.margin, -ter.half + 5)
    y1 = min(max(ys) + args.margin, ter.half - 5)

    cands = []
    y = y0
    while y < y1:
        x = x0
        while x < x1:
            cands.append((x + rng.uniform(-0.45, 0.45) * args.spacing,
                          y + rng.uniform(-0.45, 0.45) * args.spacing))
            x += args.spacing
        y += args.spacing
    rng.shuffle(cands)

    trunks = Mesh()
    crowns = [Mesh() for _ in range(4)]
    shrubs = [Mesh() for _ in range(2)]
    n_tree = n_shrub = 0
    for px, py in cands:
        if min(math.hypot(px - t["x"], py - t["y"]) for t in turb) < 35:
            continue
        if math.hypot(px, py) < 25 or near_building(px, py, polys):
            continue
        c = min(int((px + ter.half) / ter.extent * ts), ts - 1)
        r = min(int((ter.half - py) / ter.extent * ts), ts - 1)
        g, b = exg[r, c], bright[r, c]
        z = ter.ground_z(px, py)
        if z is None:
            continue
        if g > 0.06 and b < 0.36 and n_tree < args.max_trees \
                and rng.random() < min(1.0, (g - 0.04) * 9):
            h = rng.uniform(5.0, 12.0)
            cr = h * rng.uniform(0.26, 0.36)
            ch = z + h * rng.uniform(0.6, 0.7)
            trunk(trunks, px, py, z, 0.022 * h, 0.012 * h, h * 0.62)
            m = crowns[rng.randrange(4)]
            for _ in range(rng.randint(3, 4)):
                a = rng.uniform(0, 2 * math.pi)
                d = rng.uniform(0.15, 0.5) * cr
                lr = cr * rng.uniform(0.55, 0.8)
                lobe(m, px + d * math.cos(a), py + d * math.sin(a),
                     ch + rng.uniform(-0.25, 0.3) * cr, lr, lr * 0.85, rng)
            n_tree += 1
        elif g > 0.03 and n_shrub < args.max_shrubs \
                and rng.random() < min(0.6, (g - 0.02) * 6):
            w = rng.uniform(0.6, 1.6)
            m = shrubs[rng.randrange(2)]
            for _ in range(rng.randint(1, 2)):
                lobe(m, px + rng.uniform(-0.3, 0.3) * w,
                     py + rng.uniform(-0.3, 0.3) * w, z + w * 0.4,
                     w * rng.uniform(0.7, 1.0), w * 0.6, rng, 0.18, fine=False)
            n_shrub += 1

    name = f"{args.terrain_model}_foliage"
    mdir = os.path.join(repo, "models", name)
    os.makedirs(os.path.join(mdir, "meshes"), exist_ok=True)
    for f in os.listdir(os.path.join(mdir, "meshes")):
        os.remove(os.path.join(mdir, "meshes", f))
    parts = [("trunks", trunks, "0.26 0.18 0.11"),
             ("crown_a", crowns[0], "0.09 0.21 0.07"),
             ("crown_b", crowns[1], "0.14 0.28 0.09"),
             ("crown_c", crowns[2], "0.20 0.33 0.10"),
             ("crown_d", crowns[3], "0.27 0.32 0.12"),
             ("shrub_a", shrubs[0], "0.22 0.31 0.11"),
             ("shrub_b", shrubs[1], "0.31 0.34 0.15")]
    vis, tris = [], 0
    for nm, mesh, col in parts:
        if not mesh.f:
            continue
        tris += mesh.write(os.path.join(mdir, "meshes", f"{nm}.obj"), nm)
        amb = " ".join(f"{float(v) * 0.75:.3f}" for v in col.split())
        vis.append(f'      <visual name="{nm}"><geometry><mesh><uri>model://{name}/'
                   f'meshes/{nm}.obj</uri></mesh></geometry><material><ambient>{amb} 1'
                   f'</ambient><diffuse>{col} 1</diffuse><specular>0.04 0.04 0.04 1'
                   f'</specular></material></visual>')
    with open(os.path.join(mdir, "model.sdf"), "w") as f:
        f.write(f'<?xml version="1.0" ?>\n<!-- Generated by tools/gen_foliage.py: '
                f'{n_tree} trees, {n_shrub} shrubs, {tris} triangles, visual only. -->\n'
                f'<sdf version="1.9">\n  <model name="{name}">\n    <static>true</static>\n'
                f'    <link name="link">\n' + "\n".join(vis) +
                '\n    </link>\n  </model>\n</sdf>\n')
    with open(os.path.join(mdir, "model.config"), "w") as f:
        f.write(f'<?xml version="1.0"?>\n<model><name>{name}</name><version>2.0</version>'
                f'<sdf version="1.9">model.sdf</sdf></model>\n')
    print(f"  {n_tree} trees, {n_shrub} shrubs, {tris} triangles -> {mdir}")


if __name__ == "__main__":
    main()
