#!/usr/bin/env python3
"""
gen_buildings.py
================

Extrudes building footprints from an OpenStreetMap GeoJSON export into 3D
buildings standing on the terrain, as a single static Gazebo model.

Input
-----
A GeoJSON FeatureCollection exported from overpass-turbo.eu (Export ->
GeoJSON). Features with a "building" property and Polygon/MultiPolygon
geometry become buildings; everything else (roads, turbines) is ignored.
The same export feeds the road tool later.

Geometry
--------
Height comes from building:levels (3.2 m per level) or height tags when
present, otherwise one or two storeys at random, typical of rural Kerala.
Roof style follows the footprint: four-cornered footprints get a pitched
terracotta gable roof along their long axis, the common Kerala house form;
other shapes get a flat concrete roof with a low parapet. Walls extend
down below the lowest terrain point under the footprint, so buildings on
slopes sit into the hillside instead of floating.

Walls use three plaster colours and roofs two, each colour one mesh, so
the whole settlement is about five draw calls. Buildings have box
collisions approximating each footprint's bounding rectangle, so vehicles
cannot drive through them.

Output: models/<terrain>_buildings/{model.sdf, model.config, meshes/*.obj}

Usage
  python3 tools/gen_buildings.py --terrain-model attappadi \
      --geojson ~/Downloads/attappadi_osm.geojson
"""

import argparse
import json
import math
import os
import random

from terrain_io import Terrain


class Soup:
    """Flat-shaded triangle soup: buildings are hard-edged."""

    def __init__(self):
        self.t = []

    def tri(self, a, b, c):
        u = [b[i] - a[i] for i in range(3)]
        v = [c[i] - a[i] for i in range(3)]
        n = (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2],
             u[0] * v[1] - u[1] * v[0])
        m = math.sqrt(sum(k * k for k in n))
        if m > 1e-9:
            self.t.append((a, b, c, tuple(k / m for k in n)))

    def quad(self, a, b, c, d):
        self.tri(a, b, c)
        self.tri(a, c, d)

    def write(self, path):
        with open(path, "w") as f:
            f.write("# Generated by gen_buildings.py\n")
            for a, b, c, _ in self.t:
                for p in (a, b, c):
                    f.write(f"v {p[0]:.3f} {p[1]:.3f} {p[2]:.3f}\n")
            for *_, n in self.t:
                f.write(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n")
            for i in range(len(self.t)):
                f.write(f"f {3*i+1}//{i+1} {3*i+2}//{i+1} {3*i+3}//{i+1}\n")
        return len(self.t)


def ccw(pts):
    area = sum(pts[i][0] * pts[(i + 1) % len(pts)][1] -
               pts[(i + 1) % len(pts)][0] * pts[i][1] for i in range(len(pts)))
    return pts if area > 0 else pts[::-1]


def triangulate(pts):
    """Ear clipping for a simple counter-clockwise polygon."""
    idx = list(range(len(pts)))
    tris, guard = [], 0

    def inside(p, a, b, c):
        def s(p1, p2, p3):
            return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])
        d1, d2, d3 = s(p, a, b), s(p, b, c), s(p, c, a)
        return not ((d1 < 0 or d2 < 0 or d3 < 0) and (d1 > 0 or d2 > 0 or d3 > 0))

    while len(idx) > 3 and guard < 10000:
        guard += 1
        for k in range(len(idx)):
            i0, i1, i2 = idx[k - 1], idx[k], idx[(k + 1) % len(idx)]
            a, b, c = pts[i0], pts[i1], pts[i2]
            if (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]) <= 0:
                continue
            if any(inside(pts[j], a, b, c) for j in idx if j not in (i0, i1, i2)):
                continue
            tris.append((i0, i1, i2))
            idx.pop(k)
            break
        else:
            break
    if len(idx) == 3:
        tris.append(tuple(idx))
    return tris


def building_height(props, rng):
    for key in ("height", "building:height"):
        try:
            return max(3.0, float(str(props[key]).split()[0]))
        except (KeyError, ValueError):
            pass
    try:
        return max(3.0, float(props["building:levels"]) * 3.2)
    except (KeyError, ValueError):
        return rng.choice([3.4, 3.6, 3.8, 6.6, 7.0])


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--terrain-model", required=True)
    ap.add_argument("--geojson", required=True)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--seed", type=int, default=11)
    args = ap.parse_args()

    repo = os.path.abspath(os.path.expanduser(args.repo))
    ter = Terrain(os.path.join(repo, "models", args.terrain_model))
    rng = random.Random(args.seed)
    data = json.load(open(os.path.expanduser(args.geojson)))

    walls = [Soup() for _ in range(3)]
    roof_tile, roof_flat = Soup(), Soup()
    cols, n_b, n_skip = [], 0, 0
    for ft in data.get("features", []):
        g, pr = ft.get("geometry") or {}, ft.get("properties") or {}
        if "building" not in pr or g.get("type") not in ("Polygon", "MultiPolygon"):
            continue
        rings = [g["coordinates"][0]] if g["type"] == "Polygon" else \
            [p[0] for p in g["coordinates"]]
        for ring in rings:
            if ring[0] == ring[-1]:
                ring = ring[:-1]
            if len(ring) < 3:
                continue
            pts = ccw([ter.latlon_to_world(la, lo) for lo, la in ring])
            gz = [ter.ground_z(x, y) for x, y in pts]
            if any(z is None for z in gz):
                n_skip += 1
                continue
            base = min(gz) - 0.4
            top = max(gz) + building_height(pr, rng)
            w = walls[rng.randrange(3)]
            n = len(pts)
            for i in range(n):
                a, b = pts[i], pts[(i + 1) % n]
                w.quad((a[0], a[1], base), (b[0], b[1], base),
                       (b[0], b[1], top), (a[0], a[1], top))

            edges = [math.hypot(pts[(i + 1) % n][0] - pts[i][0],
                                pts[(i + 1) % n][1] - pts[i][1]) for i in range(n)]
            if n == 4 and rng.random() < 0.65:
                # Gable roof along the long axis, 0.5 m eaves overhang.
                k = 0 if edges[0] + edges[2] >= edges[1] + edges[3] else 1
                p0, p1, p2, p3 = [pts[(k + j) % 4] for j in range(4)]
                span = (edges[(k + 1) % 4] + edges[(k + 3) % 4]) / 2
                rise = span * 0.32
                m01 = ((p0[0] + p3[0]) / 2, (p0[1] + p3[1]) / 2)
                m23 = ((p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2)
                ridge_a, ridge_b = (*m01, top + rise), (*m23, top + rise)
                roof_tile.quad((p0[0], p0[1], top), (p1[0], p1[1], top), ridge_b, ridge_a)
                roof_tile.quad((p2[0], p2[1], top), (p3[0], p3[1], top), ridge_a, ridge_b)
                w.tri((p3[0], p3[1], top), (p0[0], p0[1], top), ridge_a)
                w.tri((p1[0], p1[1], top), (p2[0], p2[1], top), ridge_b)
            else:
                for i0, i1, i2 in triangulate(pts):
                    roof_flat.tri((*pts[i0], top), (*pts[i1], top), (*pts[i2], top))
                for i in range(n):   # parapet
                    a, b = pts[i], pts[(i + 1) % n]
                    w.quad((a[0], a[1], top), (b[0], b[1], top),
                           (b[0], b[1], top + 0.9), (a[0], a[1], top + 0.9))

            xs, ys = [p[0] for p in pts], [p[1] for p in pts]
            cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
            h = top - base
            cols.append(f'        <collision name="b{n_b}"><pose>{cx:.2f} {cy:.2f} '
                        f'{base + h / 2:.2f} 0 0 0</pose><geometry><box><size>'
                        f'{max(xs) - min(xs):.2f} {max(ys) - min(ys):.2f} {h:.2f}'
                        f'</size></box></geometry></collision>')
            n_b += 1

    name = f"{args.terrain_model}_buildings"
    mdir = os.path.join(repo, "models", name)
    os.makedirs(os.path.join(mdir, "meshes"), exist_ok=True)
    parts = [("walls_a", walls[0], "0.86 0.84 0.78"),
             ("walls_b", walls[1], "0.93 0.88 0.70"),
             ("walls_c", walls[2], "0.78 0.82 0.80"),
             ("roof_tile", roof_tile, "0.62 0.28 0.16"),
             ("roof_flat", roof_flat, "0.58 0.57 0.54")]
    vis = []
    for nm, soup, col in parts:
        if not soup.t:
            continue
        soup.write(os.path.join(mdir, "meshes", f"{nm}.obj"))
        amb = " ".join(f"{float(v) * 0.7:.3f}" for v in col.split())
        vis.append(f'        <visual name="{nm}"><geometry><mesh><uri>model://{name}/'
                   f'meshes/{nm}.obj</uri></mesh></geometry><material><ambient>{amb} 1'
                   f'</ambient><diffuse>{col} 1</diffuse><specular>0.1 0.1 0.1 1'
                   f'</specular></material></visual>')
    with open(os.path.join(mdir, "model.sdf"), "w") as f:
        f.write(f'<?xml version="1.0" ?>\n<!-- Generated by tools/gen_buildings.py from '
                f'OSM footprints: {n_b} buildings. -->\n<sdf version="1.9">\n'
                f'  <model name="{name}">\n    <static>true</static>\n'
                f'    <link name="link">\n' + "\n".join(vis + cols) +
                '\n    </link>\n  </model>\n</sdf>\n')
    with open(os.path.join(mdir, "model.config"), "w") as f:
        f.write(f'<?xml version="1.0"?>\n<model><name>{name}</name><version>1.0</version>'
                f'<sdf version="1.9">model.sdf</sdf></model>\n')
    print(f"  {n_b} buildings ({n_skip} outside terrain skipped) -> {mdir}")


if __name__ == "__main__":
    main()
