#!/usr/bin/env python3
"""
validate_live.py
================

Live end-to-end georeferencing test, run against the running Gazebo world.

For each turbine, spawns a small weightless probe carrying a Gazebo NavSat
(GPS) sensor one metre above the turbine base, reads the latitude,
longitude and altitude Gazebo reports there, and compares them with the
turbine's surveyed coordinates and DEM elevation. The same NavSat model
feeds PX4's GPS, so this checks the whole chain the drone relies on:
surveyed coordinate -> world position -> simulated GPS reading.

Requires the world to be running (not paused). No PX4 needed.

Usage
  python3 tools/validate_live.py --terrain-model attappadi \
      --world attappadi_windfarm
"""

import argparse
import math
import os
import re
import subprocess
import time

from terrain_io import Terrain, read_turbines

PROBE = """<?xml version="1.0"?>
<sdf version="1.9"><model name="{name}"><pose>{x} {y} {z} 0 0 0</pose>
<link name="link"><gravity>false</gravity>
<inertial><mass>0.1</mass><inertia><ixx>1e-4</ixx><iyy>1e-4</iyy><izz>1e-4</izz>
<ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>
<visual name="v"><geometry><sphere><radius>0.4</radius></sphere></geometry>
<material><ambient>1 0 1 1</ambient><diffuse>1 0 1 1</diffuse></material></visual>
<sensor name="navsat" type="navsat"><always_on>1</always_on><update_rate>10</update_rate>
<topic>/validation/{name}/navsat</topic></sensor></link></model></sdf>
"""


def gz(cmd, timeout=15):
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout).stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--terrain-model", required=True)
    ap.add_argument("--world", required=True)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--out", default="docs/validation")
    a = ap.parse_args()
    repo = os.path.abspath(os.path.expanduser(a.repo))
    ter = Terrain(os.path.join(repo, "models", a.terrain_model))
    turb = read_turbines(os.path.join(repo, "config", "turbines.yaml"))

    rows, worst_h = [], 0.0
    for t in turb:
        name = "gps_probe_" + t["id"].replace("turbine_", "t")
        z = t["ground_z"] + 1.0
        path = f"/tmp/{name}.sdf"
        open(path, "w").write(PROBE.format(name=name, x=t["x"], y=t["y"], z=z))
        gz(["gz", "service", "-s", f"/world/{a.world}/create", "--reqtype",
            "gz.msgs.EntityFactory", "--reptype", "gz.msgs.Boolean", "--timeout",
            "5000", "--req", f'sdf_filename: "{path}" name: "{name}"'])
        time.sleep(1.5)
        msg = gz(["gz", "topic", "-e", "-n", "1", "-t", f"/validation/{name}/navsat"])
        vals = dict(re.findall(r"(latitude_deg|longitude_deg|altitude):\s*(-?[\d.eE+-]+)", msg))
        if len(vals) < 3:
            rows.append(f"| {t['id']} | no NavSat reading (is the world running?) | | | |")
            continue
        la, lo, alt = (float(vals[k]) for k in ("latitude_deg", "longitude_deg", "altitude"))
        dh = math.hypot((lo - t["lon"]) * 111320 * math.cos(math.radians(la)),
                        (la - t["lat"]) * 110574)
        exp_alt = ter.elev0 + z
        worst_h = max(worst_h, dh)
        rows.append(f"| {t['id']} | {la:.7f}, {lo:.7f} | {t['lat']:.7f}, {t['lon']:.7f} | "
                    f"{dh * 100:.1f} | {alt - exp_alt:+.2f} |")
        gz(["gz", "service", "-s", f"/world/{a.world}/remove", "--reqtype",
            "gz.msgs.Entity", "--reptype", "gz.msgs.Boolean", "--timeout", "3000",
            "--req", f'name: "{name}" type: MODEL'])
        print(f"  {t['id']}: horizontal error {dh * 100:.1f} cm, altitude "
              f"{alt - exp_alt:+.2f} m")

    os.makedirs(os.path.join(repo, a.out), exist_ok=True)
    with open(os.path.join(repo, a.out, "live_gps.md"), "w") as f:
        f.write("# Live GPS validation\n\nGenerated by `tools/validate_live.py` against "
                f"the running `{a.world}` world. A NavSat probe was spawned 1 m above "
                "each turbine base; its reported position is compared with the surveyed "
                "turbine coordinates.\n\n| Turbine | Gazebo GPS (lat, lon) | Surveyed "
                "(lat, lon) | Horizontal error (cm) | Altitude error (m) |\n"
                "|---|---|---|---|---|\n" + "\n".join(rows) +
                f"\n\nWorst horizontal error: **{worst_h * 100:.1f} cm**. Altitude error "
                "includes Earth curvature (Gazebo's GPS model is a tangent plane on the "
                "ellipsoid, the heightmap is flat): a few centimetres at 1 km.\n")
    print(f"  worst horizontal error {worst_h * 100:.1f} cm -> {a.out}/live_gps.md")


if __name__ == "__main__":
    main()
